### ISSUE TITLE
Animation support 

### ISSUE THREAD

**Issue by Chathula** [TBouder/react-native-placeholder#1]
Can you add animation support to this?

Like this...

http://cloudcannon.com/deconstructions/2014/11/15/facebook-content-placeholder-deconstruction.html

**Comment by TBouder** [comment]
Hi !

The module will be rewrite soon (the code and the usage is too complex), but there is already this kind of animation.
Do you want me to add a way to customize it ?

Thanks

**Comment by Chathula** [comment]
yes sure.. with it this will be much better.. :D 

can u suggest if there is any other for React Native?

**Comment by TBouder** [comment]
This one seems good !
https://github.com/Skahrz/rn-placeholder

**Comment by Chathula** [comment]
Thank you very much!!
